#pragma once
#include "../RTBEngineAPI.h"
#include "ModelLoader.h"
#include "Material.h"
#include "Texture.h"
#include "../Core/ResourceManager.h"
#include "../RTBEngine.h"
#include <vector>
#include <unordered_map>
#include <string>
#include <filesystem>

namespace RTBEngine {
    namespace ECS {
        class Scene;
        class GameObject;
    }
}

namespace RTBEngine {
    namespace Rendering {

        struct FbxBindingContext {
            Core::ResourceManager& resources;
            std::string modelPath;
            const ModelData& modelData;
        };

        struct FbxBindingResult {
            std::vector<Mesh*> meshes;                     // Mesh list (usually modelData.meshes)
            std::vector<Material*> meshMaterials;          // Per-mesh materials (non-owned)
            std::vector<Texture*> embeddedTextureObjects;  // Textures created from embedded data (owned elsewhere)
        };

        // Build meshes and per-mesh materials from ModelData.
        // Reuses materials by FBX material name and uses embedded or external textures.
        inline FbxBindingResult BuildMeshesAndMaterials(const FbxBindingContext& ctx)
        {
            FbxBindingResult result;
            result.meshes = ctx.modelData.meshes;

            // Build name-per-embedded-texture map (same logic as ContentBrowserPanel)
            std::string fbxStem = std::filesystem::path(ctx.modelPath).stem().string();
            std::filesystem::path fbxDir = std::filesystem::path(ctx.modelPath).parent_path();

            std::vector<std::string> texNames(ctx.modelData.embeddedTextures.size());
            for (size_t i = 0; i < ctx.modelData.materials.size(); i++) {
                int idx = ctx.modelData.materials[i].embeddedTextureIndex;
                if (idx < 0 || idx >= static_cast<int>(texNames.size())) continue;
                if (!texNames[idx].empty()) continue;
                std::string matName = ctx.modelData.materials[i].name;
                for (char& c : matName)
                    if (c == '/' || c == '\\' || c == ':' || c == '*' || c == '?' || c == '"' || c == '<' || c == '>' || c == '|') c = '_';
                texNames[idx] = matName.empty() ? ("tex_" + std::to_string(idx)) : matName;
            }

            // Build embedded textures — prefer .texture asset files on disk
            std::vector<Texture*> embeddedTextures;
            embeddedTextures.reserve(ctx.modelData.embeddedTextures.size());

            for (size_t i = 0; i < ctx.modelData.embeddedTextures.size(); i++) {
                const EmbeddedTexture& embTex = ctx.modelData.embeddedTextures[i];
                std::string name = texNames[i].empty()
                    ? (fbxStem + "_tex" + std::to_string(i))
                    : (fbxStem + "_" + texNames[i]);

                // Try loading from .texture asset file (generated by ContentBrowser)
                Texture* tex = nullptr;
                std::string textureAssetPath = (fbxDir / (name + ".texture")).generic_string();
                std::string resolvedTextureAssetPath = ctx.resources.ResolvePathForRead(textureAssetPath);
                if (std::filesystem::exists(resolvedTextureAssetPath)) {
                    tex = ctx.resources.LoadTextureAsset(textureAssetPath);
                }

                // Also check with .png/.jpg extensions for .texture file
                if (!tex) {
                    for (const char* ext : { ".png", ".jpg" }) {
                        std::filesystem::path candidateTextureAssetPath = fbxDir / (name + ext);
                        candidateTextureAssetPath.replace_extension(".texture");
                        std::string candidateTextureAssetPathString = candidateTextureAssetPath.generic_string();
                        std::string resolvedCandidateTextureAssetPath = ctx.resources.ResolvePathForRead(candidateTextureAssetPathString);
                        if (std::filesystem::exists(resolvedCandidateTextureAssetPath)) {
                            tex = ctx.resources.LoadTextureAsset(candidateTextureAssetPathString);
                            if (tex) break;
                        }
                    }
                }

                // Fallback: load from embedded data and register with a synthetic path
                if (!tex) {
                    tex = new Texture();
                    bool loaded = false;

                    if (embTex.isCompressed) {
                        loaded = tex->LoadFromCompressedMemory(
                            embTex.data.data(),
                            static_cast<int>(embTex.data.size()));
                    }
                    else {
                        loaded = tex->LoadFromMemory(
                            embTex.data.data(),
                            embTex.width,
                            embTex.height,
                            embTex.channels);
                    }

                    if (loaded) {
                        // Register so Inspector shows a path instead of "[Texture Set]"
                        std::string syntheticPath = ctx.modelPath + "#" + name;
                        ctx.resources.RegisterTexture(syntheticPath, tex);
                    }
                    else {
                        RTB_WARN("[FbxBinding] Failed to load embedded texture for model: " + ctx.modelPath);
                        delete tex;
                        tex = nullptr;
                    }
                }

                embeddedTextures.push_back(tex);
            }

            result.embeddedTextureObjects = embeddedTextures;

            // Cache materials by FBX material name
            std::unordered_map<std::string, Material*> materialCache;
            result.meshMaterials.reserve(ctx.modelData.meshes.size());

            // Shader will be set by caller; we just default to nullptr here
            Shader* defaultShader = nullptr;

            for (Mesh* mesh : ctx.modelData.meshes) {
                if (!mesh) {
                    result.meshMaterials.push_back(nullptr);
                    continue;
                }

                const int matIdx = mesh->GetMaterialIndex();
                if (matIdx < 0 || matIdx >= static_cast<int>(ctx.modelData.materials.size())) {
                    result.meshMaterials.push_back(nullptr);
                    continue;
                }

                const LoadedMaterial& loadedMat = ctx.modelData.materials[matIdx];

                Material* mat = nullptr;

                if (!loadedMat.name.empty()) {
                    auto it = materialCache.find(loadedMat.name);
                    if (it != materialCache.end()) {
                        mat = it->second;
                    }
                }

                if (!mat) {
                    mat = new Material(defaultShader);

                    bool hasTexture = false;

                    if (loadedMat.embeddedTextureIndex >= 0 &&
                        loadedMat.embeddedTextureIndex < static_cast<int>(embeddedTextures.size()) &&
                        embeddedTextures[loadedMat.embeddedTextureIndex]) {
                        mat->SetTexture(embeddedTextures[loadedMat.embeddedTextureIndex]);
                        hasTexture = true;
                    }
                    else if (!loadedMat.diffuseTexturePath.empty()) {
                        Texture* tex = ctx.resources.LoadTexture(loadedMat.diffuseTexturePath);
                        if (tex) {
                            mat->SetTexture(tex);
                            hasTexture = true;
                        }
                        else {
                            RTB_WARN("[FbxBinding] Failed to load diffuse texture from FBX path: " +
                                     loadedMat.diffuseTexturePath);
                        }
                    }
                    else {
                        RTB_WARN("[FbxBinding] FBX material '" + loadedMat.name +
                                 "' has no diffuse texture or embedded texture");
                    }

                    // When a diffuse texture is present, force diffuse color to white so
                    // the FBX material color does not darken/tint the texture.
                    // FBX exporters often store a non-white diffuse color alongside the
                    // texture which causes muddy/dark rendering when multiplied in the shader.
                    if (hasTexture) {
                        mat->SetDiffuseColor(Math::Vector3(1.0f, 1.0f, 1.0f));
                    }
                    else {
                        mat->SetDiffuseColor(loadedMat.diffuseColor);
                    }

                    if (!loadedMat.name.empty()) {
                        materialCache[loadedMat.name] = mat;
                    }
                }

                result.meshMaterials.push_back(mat);
            }

            return result;
        }

        // Build a root+children hierarchy in the scene from a multi-mesh ModelData.
        // Root GameObject holds the Animator (if the FBX has animation data).
        // Each mesh gets its own child GameObject with a MeshRenderer.
        // Declared here; implemented in FbxBinding.cpp.
        RTB_API ECS::GameObject* BuildFbxHierarchy(
            ECS::Scene* scene,
            const ModelData& modelData,
            const std::string& fbxPath,
            Core::ResourceManager& resources);

    }
}


